# Generated by Django 4.0.6 on 2022-07-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(default=00000000000, max_length=11),
        ),
    ]
