# Generated by Django 4.0.6 on 2022-07-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
    ]
